### ISSUE TITLE
pinning pytest in install dependencies is incorrect

### ISSUE THREAD

**Issue by drake-mer** [flagship-io/flagship-python-sdk#17]
- this file: [requirements.txt](https://github.com/flagship-io/flagship-python-sdk/blob/master/requirements.txt)
- this file: [setup.cfg](https://github.com/flagship-io/flagship-python-sdk/blob/master/setup.cfg#L32-L38) 

Pin pytest as an install dep, which is incorrect.

At most could it be a build dependency.

**Comment by David-Flagship** [comment]
Hello @drake-mer and thanks for the issue, will check this and come back to you as soon as the problem will be solved. 

Have a nice day,

David, Product Manager for Flagship

**Comment by raf-abtasty** [comment]
Hi @drake-mer, thx for your feedback. i have merged @remihuguet PR #18 . Have a nice day.
